.\" © Richard Kettewell. See README.md for more info.
.TH rot13 1
.SH SYNOPSIS
\fBrot13 \fR[\fIPATH\fR...]
.SH DESCRIPTION
\fBrot13\fR reads from standard input or the named files,
moving each occurrence of a letter 13 places forward in the alphabet,
wrapping around past the end of the alphabet.
.SH OPTIONS
.TP
.B --help
Display help message
.TP
.B --version
Display versions string
